# Generated by Django 4.2.3 on 2023-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
